### ISSUE TITLE
Change minimum supported Gradle version to 4.3

### ISSUE THREAD

**Issue by Arthurm1** [scalacenter/bloop#1133]
The Bloop Gradle plugin doesn't work with the latest Gradle version: 6.0

It throws a NoSuchMethodException in [this](https://github.com/scalacenter/bloop/blob/2d96bcf6bb6c4ba7510ee7ad61bc090436435df3/integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/tasks/ConfigureBloopInstallTask.scala#L31) code

It seems that the plugin would need to be compiled against Gradle 4.3 or later to fix this or the above code would need to be re-written ([see Gradle Forum](https://discuss.gradle.org/t/nosuchmethoderror-with-gradle-6-0/34254)).

Changing from 3.5 to a minimum version of 4.3 would simplify the plugin in a few areas and would get rid of some of the reflection but I've no idea what versions of Gradle are in use.

3.5 was released Apr 2017 and 4.3 was released Oct 2017 so not a huge gap between upgrading.

Does anyone have a view?  I'd be happy to work on changing to 4.3.

@pkolaczk ping as you seem to be the most active Gradle user.

**Comment by jvican** [comment]
I think it makes sense to upgrade to 4.3 and drop support for 3.5 if that gives us compat with the latest Gradle version. Thanks for volunteering to take this up! What about you create a PR? @pkolaczk will chime in at some point but I think he should not be affected by the ugprade.
